name: Build

on:
  push:
    tags:
      - deploy
  workflow_dispatch:

env:
  CI: true

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.13.1
      uses: actions/setup-node@v4
      with:
        node-version: 20.13.1
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - name: List build files
      run: |
        echo $(date) > ./out/ver.txt
        ls ./out

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
